# Generated by Django 4.0 on 2022-01-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date_creation', models.DateField()),
                ('montant', models.FloatField()),
                ('etat_paiement', models.IntegerField()),
            ],
            options={
                'db_table': 'infraction',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='citoyen',
            name='id',
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='cin',
            field=models.IntegerField(db_column='CIN', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='infraction',
            name='cin_citoyen',
            field=models.ForeignKey(db_column='cin_citoyen', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.citoyen'),
        ),
    ]
